// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4nrUoocCiunDK_vBsHb8CZybZoZMDHV4',
    appId: '1:769538677401:web:89307629b7ec6e88deb608',
    messagingSenderId: '769538677401',
    projectId: 'fooddelivery-fa109',
    authDomain: 'fooddelivery-fa109.firebaseapp.com',
    storageBucket: 'fooddelivery-fa109.firebasestorage.app',
    measurementId: 'G-5YG1M1CX0Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDLAJTF0cQgBGIOP1tsydMCavSE1ZAW9A',
    appId: '1:769538677401:android:3de366b55a0aec36deb608',
    messagingSenderId: '769538677401',
    projectId: 'fooddelivery-fa109',
    storageBucket: 'fooddelivery-fa109.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCU8t7NTUQAJ1xpdxDphtHbobABrqiHucw',
    appId: '1:769538677401:ios:a98e7e3298898142deb608',
    messagingSenderId: '769538677401',
    projectId: 'fooddelivery-fa109',
    storageBucket: 'fooddelivery-fa109.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCU8t7NTUQAJ1xpdxDphtHbobABrqiHucw',
    appId: '1:769538677401:ios:a98e7e3298898142deb608',
    messagingSenderId: '769538677401',
    projectId: 'fooddelivery-fa109',
    storageBucket: 'fooddelivery-fa109.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA4nrUoocCiunDK_vBsHb8CZybZoZMDHV4',
    appId: '1:769538677401:web:aca219d74d49d1b2deb608',
    messagingSenderId: '769538677401',
    projectId: 'fooddelivery-fa109',
    authDomain: 'fooddelivery-fa109.firebaseapp.com',
    storageBucket: 'fooddelivery-fa109.firebasestorage.app',
    measurementId: 'G-MRJFQF32R5',
  );
}
